import type { Metadata } from "next";
import {
  DynaPuff,
  Inter,
  Playfair,
  Raleway,
  Space_Mono,
} from "next/font/google";
import "./globals.css";
import { ThemeWrapper } from "@/components/ThemeWrapper";
import Container from "@/components/Container";

const raleway = Raleway({
  variable: "--font-raleway",
});

const spaceMono = Space_Mono({
  variable: "--font-space-mono",
  subsets: ["latin"],
  weight: "400",
});

const dynaPuff = DynaPuff({
  variable: "--font-dyna-puff",
  subsets: ["latin"],
});

const inter = Inter({
  variable: "--font-inter",
  subsets: ["latin"],
});

const platfaire = Playfair({
  variable: "--font-playfair",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en" suppressHydrationWarning>
      <body
        className={`${raleway.variable} ${spaceMono.variable} ${dynaPuff.variable} ${inter.variable} ${platfaire.variable} antialiased font-body`}
      >
        <ThemeWrapper>
          <Container>{children}</Container>
        </ThemeWrapper>
      </body>
    </html>
  );
}
